apiVersion: apps/v1
kind: Deployment
metadata:
  name: goblog-frontend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          #image: andrewwon79/goblog-frontend:1.6
          image: 616526550235.dkr.ecr.us-east-2.amazonaws.com/goblog_frontend
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: goblog-config
          - secretRef:
              name: goblog-secret